# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # box name
  config.vm.box = "xenial-server-cloudimg-amd64-vagrant.box"
  config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"
  config.vm.provision "shell", path: "./bin/init.sh"

  # port forward
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # network adapter
  config.vm.network "private_network", ip: "192.168.33.10"

  # VM configure
  config.vm.provider "virtualbox" do |vb|
      vb.name = "bk_vagrant"
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
  end
end