# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # box name
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202407.23.0"
  config.vm.synced_folder ".", "/vagrant", owner: "www-data", group: "www-data"
  config.vm.provision "shell", path: "./bin/init.sh"

  # port forward
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # network adapter
  config.vm.network "private_network", ip: "192.168.33.10"

  # VM configure
  config.vm.provider "virtualbox" do |vb|
      vb.name = "bk_vagrant"
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
  end
end
